version: '3'

services:
  email_rpc:
    container_name: email_rpc
    build: python/
    restart: always

    networks:
      - microservice
      - default

  smtp:
    container_name: email_smtp
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 478
      RELAY_USERNAME: chanawee.sat@student.mahidol.ac.edu
      RELAY_PASSWORD: xxx if google use app passwd

networks:
  default:
    external:
      name: email_network
  microservice:
    external:
      name: microservice_network
      